# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test --package-path SpaceBattleGame/SpaceBattleGame
